#!/bin/bash
tgtpath="linux_x86_64"
include="Tilengine.h"
library="libTilengine.so"
incpath="/usr/include"
libpath="/usr/lib/x86_64-linux-gnu"

cp include/$include $incpath
cp lib/$tgtpath/$library $libpath
chmod a+x $incpath/$include
chmod a+x $libpath/$library
