#!/bin/bash
name=$(uname -s)
arch=$(uname -m)

echo "Installing $name $arch"
include="Tilengine.h"
if [ $name == "Linux" ]; then
	library="libTilengine.so"
	incpath="/usr/include"
	if [ $arch == "i686" ]; then
		libpath="/usr/lib/i386-linux-gnu"
	elif [ $arch == "x86_64" ]; then
		libpath="/usr/lib/x86_64-linux-gnu"
	elif [ $arch == "armv7l" ]; then
		libpath="/usr/lib/arm-linux-gnueabihf"
	fi
elif [ $name == "Darwin" ]; then
	library="Tilengine.dylib"
	incpath="/usr/local/include"
	libpath="/usr/local/lib"
	mkdir -p $incpath
	mkdir -p $libpath
fi

cmakepath="$libpath/cmake/Tilengine"
pkgconfigpath="$libpath/pkgconfig"

cp include/$include $incpath
cp lib/$library $libpath
mkdir -p $cmakepath
sed -e "s:<library>:$library:g" -e "s:<incpath>:$incpath:g" -e "s:<libpath>:$libpath:g" tilengine-config.cmake > $cmakepath/tilengine-config.cmake
mkdir -p $pkgconfigpath
sed -e "s:<library>:$library:g" -e "s:<incpath>:$incpath:g" -e "s:<libpath>:$libpath:g" tilengine.pc > $pkgconfigpath/tilengine.pc
chmod a+x $libpath/$library
