#!/bin/bash
tgtpath="linux_i686"
include="Tilengine.h"
library="libTilengine.so"
incpath="/usr/include"
libpath="/usr/lib/i386-linux-gnu"

cp include/$include $incpath
cp lib/$tgtpath/$library $libpath
chmod a+x $incpath/$include
chmod a+x $libpath/$library
